name: Deploy pages
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        working-directory: ./docs
        run: npm install

      - name: Build
        working-directory: ./docs
        run: npm run build --base /ws-javascript-typescript-basics/

      - name: Deploy pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: ./docs/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}